"""How character creation turns attributes into skills, health and magic.

Skills are not rolled. Each of the twelve is a fixed weighted blend of two or
three attributes, plus a flat per-class modifier, and for a handful of
(class, skill) pairs the blend is skipped entirely and a flat value is stored
instead, which is how a class ends up unable to use a skill at all.

The tables live in code rather than data (a chain of `mov ax, imm / cmp
[si+0x0e], class / je` per skill, at image `0x13af3`), so unlike
`tools/sections.py` or `tools/labels.py` this module transcribes rather than
reads. What keeps the transcription honest is that the four PRE-CREATED PARTY
characters shipped in `WORLD.DAT` were generated by this same code: reproducing
all fourteen of their derived fields, for four different classes, is a check
the tables cannot pass by accident. `tests/test_levels.py` runs it.

    python tools/skills.py            # the tables
    python tools/skills.py --check    # rebuild the shipped party and diff

Casting and starting magic points come from a separate dispatch at image
`0x14ec7`, and starting health from the stamina quarter, both included here
because they are the rest of the same "what do I start with" question.
"""

from __future__ import annotations

import struct
from pathlib import Path

from levels import CLASSES, REC_SIZE, pct

# --- Where the shipped party lives -----------------------------------------

PARTY_OFFSET = 0x41D72F  # WORLD.DAT section 32, `PRE-CREATED PARTY`
PARTY_SIZE = 5000
PARTY_SLOTS = (3000, 3500, 4000, 4500)  # the four filled slots

OFF_CLASS = 0x0E
OFF_HEALTH = 0x52
OFF_MAGIC = 0x54
OFF_FIRST_ATTR = 0x3C
OFF_FIRST_SKILL = 0x58

ATTRS = ("strength", "dexterity", "stamina", "intelligence", "wisdom", "charisma")
SKILLS = ("survival", "projectile", "slashing", "bashing", "polearm", "casting",
          "mapping", "navigation", "bartering", "repair", "thievery", "linguistics")

# --- The blends ------------------------------------------------------------
#
# Percentages sum to 100 in every case, and each term is rounded to nearest on
# its own before the sum: `pct()` is applied per term, not to a total.

BLEND: dict[str, tuple[tuple[str, int], ...]] = {
    "survival":    (("strength", 10), ("dexterity", 30), ("stamina", 60)),
    "projectile":  (("strength", 80), ("dexterity", 20)),
    "slashing":    (("strength", 20), ("dexterity", 80)),
    "bashing":     (("strength", 100),),
    "polearm":     (("strength", 50), ("dexterity", 50)),
    "mapping":     (("intelligence", 90), ("wisdom", 10)),
    "navigation":  (("dexterity", 100),),
    "bartering":   (("charisma", 85), ("intelligence", 15)),
    "repair":      (("dexterity", 80), ("intelligence", 20)),
    "thievery":    (("dexterity", 100),),
    "linguistics": (("intelligence", 70), ("wisdom", 30)),
}

# Added to the blend. Any class absent from a row gets nothing.
MODIFIER: dict[str, dict[int, int]] = {
    "survival":    {1: 5, 2: 4, 3: 3, 6: 1, 9: 2},
    "projectile":  {1: 5, 3: 5, 4: -5, 5: -5, 7: -5, 8: -5},
    "slashing":    {1: 5, 4: -7, 5: -7, 6: -5, 7: -7, 8: -7, 9: -5},
    "bashing":     {1: 5, 4: -7, 5: -7, 6: -5, 7: -7, 8: -7, 9: -5},
    "polearm":     {1: 5, 4: -7, 5: -7, 6: -5, 7: -7, 8: -7, 9: -5},
    "mapping":     {1: -5, 5: -5, 6: -5, 7: 5, 8: 3, 9: 3},
    "navigation":  {2: 3, 3: 3, 6: 5, 9: 5},
    "bartering":   {1: -5, 2: 5},
    "repair":      {2: 5, 3: 3, 4: -10, 9: -5},
    "thievery":    {1: -10, 3: 5, 7: -5},
    "linguistics": {2: -5, 6: -5, 7: 3, 8: 5, 9: -5},
}

# The blend is skipped and this flat value stored. A zero here is permanent:
# the level-up's stat-add helper refuses to touch a field that is already zero,
# so the class can never learn the skill at all.
FLAT: dict[str, dict[int, int]] = {
    "bartering":   {4: 40, 7: 40, 9: 0},
    "repair":      {6: 0},
    "thievery":    {4: 0, 8: 0},
    "linguistics": {1: 0, 3: 0},
}

HEALTH_PCT_OF_STAMINA = 25  # at creation; the level-up uses 30 instead


def derived_skill(name: str, class_code: int, attrs: dict[str, int]) -> int:
    if class_code in FLAT.get(name, {}):
        return FLAT[name][class_code]
    total = sum(pct(attrs[attr], weight) for attr, weight in BLEND[name])
    return total + MODIFIER[name].get(class_code, 0)


def usable_blend_weight(class_code: int, attribute: str) -> float:
    """Skill points a class gains per extra point of an attribute.

    Only skills the class can actually use are counted: one it is locked out
    of, or one stored as a flat value for it, contributes nothing however good
    the attribute behind it. This is what makes wisdom near-worthless to a
    fighter (0.1) and charisma skill-dead for a monk, mage or marksman, whose
    bartering is a fixed number.
    """
    return sum(
        weight
        for skill, blend in BLEND.items()
        if class_code not in FLAT.get(skill, {})
        for attr, weight in blend
        if attr == attribute
    ) / 100


def casting_and_magic(class_code: int, intelligence: int, wisdom: int) -> tuple[int, int]:
    """Starting casting skill and magic points, from the dispatch at 0x14ec7.

    One blend feeds both: magic points are a quarter of it (a shift, so it
    truncates) and casting is the blend plus a small per-class bonus. Classes
    below 4 skip the dispatch entirely and get zero for both.
    """
    if class_code < 4:
        return 0, 0
    if class_code == 4:      # monk
        blend, bonus = wisdom, 10
    elif class_code == 5:    # alchemist
        blend, bonus = pct(wisdom, 75) + pct(intelligence, 25), 5
    elif class_code == 6:    # paladin
        blend = pct(wisdom, 50)
        bonus = blend - (wisdom & 1)
    elif class_code == 8:    # druid
        blend, bonus = pct(intelligence, 75) + pct(wisdom, 25), 5
    elif class_code == 9:    # marksman
        blend = pct(intelligence, 50)
        bonus = blend - (wisdom & 1)  # yes, wisdom: the parity test reads 0x84
    else:                    # mage, and anything unrecognized
        blend, bonus = intelligence, 10
    return blend + bonus, blend >> 2


def starting_health(stamina: int) -> int:
    return pct(stamina, HEALTH_PCT_OF_STAMINA)


def create(class_code: int, attrs: dict[str, int]) -> dict[str, int]:
    """Every derived field a freshly created character gets."""
    casting, magic = casting_and_magic(
        class_code, attrs["intelligence"], attrs["wisdom"])
    out = {name: derived_skill(name, class_code, attrs) for name in BLEND}
    out["casting"] = casting
    out["health"] = starting_health(attrs["stamina"])
    out["magic"] = magic
    return out


# --- The shipped party, as ground truth ------------------------------------


def shipped_party(path: str | Path = "game/WORLD.DAT") -> list[dict]:
    """The four PRE-CREATED PARTY characters, decoded."""
    blob = Path(path).read_bytes()[PARTY_OFFSET:PARTY_OFFSET + PARTY_SIZE]
    out = []
    for slot in PARTY_SLOTS:
        rec = blob[slot:slot + REC_SIZE]
        word = lambda o: struct.unpack_from("<H", rec, o)[0]  # noqa: E731
        attrs = {name: word(OFF_FIRST_ATTR + 2 * i) for i, name in enumerate(ATTRS)}
        stored = {name: word(OFF_FIRST_SKILL + 2 * i) for i, name in enumerate(SKILLS)}
        stored["health"] = word(OFF_HEALTH)
        stored["magic"] = word(OFF_MAGIC)
        out.append({
            "name": rec[:14].split(b"\0")[0].decode(),
            "class_code": word(OFF_CLASS),
            "class": CLASSES[word(OFF_CLASS)],
            "attributes": attrs,
            "stored": stored,
            # Creation writes the same numbers into both columns.
            "columns_identical": rec[0x3C:0x72] == rec[0x7C:0xB2],
        })
    return out


def check() -> list[str]:
    """Rebuild every shipped character from its attributes; return mismatches."""
    problems = []
    for who in shipped_party():
        rebuilt = create(who["class_code"], who["attributes"])
        if not who["columns_identical"]:
            problems.append(f'{who["name"]}: stat columns differ at level 1')
        for field, want in sorted(who["stored"].items()):
            if rebuilt[field] != want:
                problems.append(
                    f'{who["name"]} ({who["class"]}): {field} '
                    f'rebuilt {rebuilt[field]}, stored {want}')
    return problems


def main(argv: list[str]) -> None:
    if "--check" in argv:
        problems = check()
        for line in problems:
            print("  " + line)
        fields = sum(len(w["stored"]) for w in shipped_party())
        print(f'{fields - len(problems)}/{fields} derived fields reproduced')
        return

    print(f"{'skill':<12} {'blend':<38} class adjustments")
    for name in SKILLS:
        if name == "casting":
            print(f"{name:<12} {'(separate dispatch; see below)':<38}")
            continue
        blend = " + ".join(f"{w}% {a}" for a, w in BLEND[name])
        bits = [f"{CLASSES[c]} {v:+d}" for c, v in sorted(MODIFIER[name].items())]
        flat = [f"{CLASSES[c]} = {v} flat" for c, v in sorted(FLAT.get(name, {}).items())]
        print(f"{name:<12} {blend:<38} {', '.join(bits + flat)}")
    print()
    print("casting / magic points, from intelligence (I) and wisdom (W):")
    for code in range(4, 10):
        cast, magic = casting_and_magic(code, 60, 60)
        print(f"  {CLASSES[code]:<10} at I=W=60 -> casting {cast}, magic {magic}")
    print("  fighter, merchant and rogue get 0 for both")
    print()
    print(f"starting health = {HEALTH_PCT_OF_STAMINA}% of stamina")


if __name__ == "__main__":
    import sys

    main(sys.argv[1:])
